### ISSUE TITLE
ошибка соединения при старте

### ISSUE THREAD

**Issue by alexstreamline** [alexstreamline/CardioMonitor#145]
![_4](https://user-images.githubusercontent.com/3107305/53543503-f87fb280-3b33-11e9-93c3-5a3001c15d17.png)
судя по логам - пытались начать слушать уже имеющуюся пару IP/port
[main.log](https://github.com/alexstreamline/CardioMonitor/files/2913532/main.log)
[trace.log](https://github.com/alexstreamline/CardioMonitor/files/2913533/trace.log)
[error.log](https://github.com/alexstreamline/CardioMonitor/files/2913534/error.log)

**Comment by Markeli** [comment]
Какой сценарий воспроизведения?

**Comment by Markeli** [comment]
Короче, добавил дополнительное закрытие обработчика сеанса и отключение от оборудования при закрытии страницы сеанса.
Проверять в `0.7` или более новой версии.
