### ISSUE TITLE
Ошибка экг при старте 3 из 3 повторения

### ISSUE THREAD

**Issue by alexstreamline** [alexstreamline/CardioMonitor#146]
[main.log](https://github.com/alexstreamline/CardioMonitor/files/2913536/main.log)
[trace.log](https://github.com/alexstreamline/CardioMonitor/files/2913537/trace.log)
[error.log](https://github.com/alexstreamline/CardioMonitor/files/2913538/error.log)
![_5](https://user-images.githubusercontent.com/3107305/53543594-4bf20080-3b34-11e9-96ce-f5049eaeaf30.png)

**Comment by Markeli** [comment]
Судя по логам, ошибка была вызвана проблемой соединения с монитором. Само исключения со скрина исправлено.
Проверять в `0.7` или более новой версии.
