### ISSUE TITLE
ECG visualisation control

### ISSUE THREAD

**Issue by Markeli** [alexstreamline/CardioMonitor#2]
Необходимо реализовать элемент управления для визуализации ЭКГ, принимаемой с монитора. Формат данных представлен ниже. 
![image](https://cloud.githubusercontent.com/assets/5919274/8147675/a52a3bb2-1280-11e5-933b-ac4967b7851a.png)
Элемент управления должен отображать данные в виде графика. Необходимо реализовать возможность выделения фрагмента графика, сохранение его в файл, сохранение всех данных в файл. Элемент управления должен уметь работать в реальном времени, отображая свежие данные, полученные от монитора. 
Элемент управления должен уметь выделять разные участки графика (до процедуры, в процессе процедуры, ключевые точки, после процедуры).
Примерный вариант контрола и его расположение представлены на рисунке.
![image](https://cloud.githubusercontent.com/assets/5919274/8147693/78e16728-1281-11e5-846d-3aff7bc359e6.png)

**Comment by Markeli** [comment]
https://visualstudiogallery.msdn.microsoft.com/d09aa844-247a-4aa6-b591-cca32f1b8b3f

**Comment by Markeli** [comment]
d3js

**Comment by Markeli** [comment]
http://habrahabr.ru/post/206918/

**Comment by Markeli** [comment]
http://habrahabr.ru/post/206918/

**Comment by Markeli** [comment]
http://stackoverflow.com/questions/952657/most-performant-way-to-graph-thousands-of-data-points-with-wpf
http://stackoverflow.com/questions/1150060/how-to-draw-line-of-ten-thousands-of-points-with-wpf-within-0-5-second

**Comment by alexstreamline** [comment]
последним ты скидывал мне вот эту штуку
https://github.com/Live-Charts/Live-Charts

**Comment by Markeli** [comment]
Считаем, что все сделали - один отвод.
