### ISSUE TITLE
Работа с флоуметром

### ISSUE THREAD

**Issue by Markeli** [alexstreamline/CardioMonitor#27]
Работа с флоуметром.
На данном этапе используется врачом вручную для определения частоты и затем ввода полученного значения в специальное поле при старте сеанса.

**Comment by alexstreamline** [comment]
флоуметр как то уплыл за скобки, еще раз уточню по его поводу

**Comment by Markeli** [comment]
Жду уточнений

**Comment by alexstreamline** [comment]
на текущем этапе в составе ПАК не используется
