### ISSUE TITLE
Гибкая схема выбора ключевых точек

### ISSUE THREAD

**Issue by Markeli** [alexstreamline/CardioMonitor#28]
Максимальный угол | кол-во контр.   точек | точка 1 | точка 2 | точка 3 | точка 4 | точка 5 | точка 6 | точка 7
-- | -- | -- | -- | -- | -- | -- | -- | --
7,5 | 3 | 0 | 7,5 | 0 |   |   |   |  
9 | 3 | 0 | 9 | 0 |   |   |   |  
10,5 | 3 | 0 | 10,5 | 0 |   |   |   |  
12 | 3 | 0 | 12 | 0 |   |   |   |  
13,5 | 5 | 0 | 6 | 13,5 | 6 | 0 |   |  
15 | 5 | 0 | 7,5 | 15 | 7,5 | 0 |   |  
16,5 | 5 | 0 | 7,5 | 16,5 | 7,5 | 0 |   |  
18 | 5 | 0 | 9 | 18 | 9 | 0 |   |  
19,5 | 5 | 0 | 9 | 19,5 | 9 | 0 |   |  
21 | 5 | 0 | 10,5 | 21 | 10,5 | 0 |   |  
22,5 | 7 | 0 | 7,5 | 15 | 22,5 | 15 | 7,5 | 0
24 | 7 | 0 | 7,5 | 15 | 24 | 15 | 7,5 | 0
25,5 | 7 | 0 | 9 | 16,5 | 25,5 | 16,5 | 9 | 0
27 | 7 | 0 | 9 | 18 | 27 | 18 | 9 | 0
28,5 | 7 | 0 | 9 | 19,5 | 28,5 | 19,5 | 9 | 0
30 | 7 | 0 | 10,5 | 19,5 | 30 | 19,5 | 10,5 | 0
31,5 | 7 | 0 | 10,5 | 21 | 31,5 | 21 | 10,5 | 0

**Comment by alexstreamline** [comment]
реализовано
