### ISSUE TITLE
Отказоустойчивость накачки

### ISSUE THREAD

**Issue by Markeli** [alexstreamline/CardioMonitor#33]
В случае, если замерить давление (осуществить накачку) не удалось, ПО пробует повторить попытку еще 2 раза, после чего сообщает об ошибке, сеанс при этом не запускается.
В ходе сеанса при ошибке накачки (не удалось корректно измерить давление) ПО пробует измерить его повторно 1 раз.

**Comment by Markeli** [comment]
@alexstreamline это же только при старте сенаса? В остальных случаях просто проглатываем ошибку?

**Comment by alexstreamline** [comment]
Эту инфу буду возвращать я на основе статуса накачки, просто определимся как именно.

**Comment by Markeli** [comment]
Инфу о том, что как завершилась накачка?

**Comment by alexstreamline** [comment]
@Markeli да, как завершилась попытка измерения давления
