### ISSUE TITLE
Информирование о подключении нового оборудования

### ISSUE THREAD

**Issue by Markeli** [alexstreamline/CardioMonitor#34]
В случае возникновения ошибок в ходе работы ПО, БД или присоединенного оборудования (изделие, кардиомонитор) ПО информирует об этом пользователя с помощью специальных информационных сообщений.

**Comment by Markeli** [comment]
@alexstreamline это жесть! Это тяжело, как мы такое в ТЗ пропустили?

**Comment by alexstreamline** [comment]
Так у нас вроде примерно это и было? Сообщения типа "нет подключения к кровати", "ошибка записи в БД" и т.д.

**Comment by Markeli** [comment]
Поведение при ошибках понятно. А вот на счет нового оборудования. Мы должны отслеживать подключения?

**Comment by alexstreamline** [comment]
@Markeli думаю, не обязательно сразу при подключении, можно просто проверять наличие устройства перед стартом сеанса/использованием устройства
хотя мб это сделать через таймер опросник, который будет в частности чекать наличие коннекта и запускать соответствующие события

**Comment by Markeli** [comment]
Нафиг это. Мы не держим открытыми соединения. Сообщения об отсутствии подлючения к БД/оборудовании во время сеанса выводим.
