### ISSUE TITLE
Настройка критических параметров, влияющих на выполнение сеанса

### ISSUE THREAD

**Issue by Markeli** [alexstreamline/CardioMonitor#36]
![image](https://user-images.githubusercontent.com/5919274/30638619-b12ebaf2-9e04-11e7-8eb4-0591ee790c51.png)
О чем речь?

**Comment by alexstreamline** [comment]
@Markeli у меня стойкое ощущение что это было написано "чтобы было", ну или про запас, мало ли какие там параметры подшаманить при обмене с кроватью. Пока не бери в голову.
