### ISSUE TITLE
Проведение дополнительного замера

### ISSUE THREAD

**Issue by Markeli** [alexstreamline/CardioMonitor#37]
Из ТЗ:

`
После завершения сеанса (именно сеанса, а не любого повторения) перед сохранением результатов в БД есть возможность провести дополнительный замер всех значений из таблицы + ЭКГ нажатием на кнопку “перемерить”, значения при этом запишутся в последнюю строчку (угол 0). 
`
Записать надо будет в последнюю строчку последнего повторения?

**Comment by alexstreamline** [comment]
@Markeli да, именно так.
