### ISSUE TITLE
Определение итераций для запроса параметров

### ISSUE THREAD

**Issue by Markeli** [alexstreamline/CardioMonitor#38]
Ребят надо попросить, чтобы в номере итерации, для которой надо снимать показатели, не было первой и последней. Это единственное "секретное", что должен знать наш софт. Или пусть добавляют в регистр еще одно поле, в котором будем общее количество итераций в данном цикле.

**Comment by alexstreamline** [comment]
Если я правильно понимаю, у нас есть номер текущего повторения, итерации внутри повторения и шага внутри итерации (+ углы). Факт того, что в данной итерации нужно запрашивать накачку или снимать экг я буду вычислять сам из таблички. Общее количество итераций я могу посчитать сам из нее же.
