### ISSUE TITLE
Окончание повторения

### ISSUE THREAD

**Issue by Markeli** [alexstreamline/CardioMonitor#39]
Как мы можем узнать о завершении повторения? О завершении сеанса? Есть ли пауза между двумя повторениями? Что должно быть в момент перехода отображаться в приложении?

**Comment by Markeli** [comment]
О завершении сеанса сможем понять, если будем знать о завершении цикла. Мы знаем общее количество циклов и текущий цикл.

**Comment by alexstreamline** [comment]
о завершении повторения и сеанса будем узнавать максимально просто  - сравнивать количество заданных повторений и рассчитанное количество итераций с их текущими значениями. Можно по идее описать эту логику в классе и генерить события. В момент перехода мы меняем значения в поле "номер повторения" на UI, можем какое нибудь сообщение в лог поле писать, мол "старт нового повторения"

**Comment by alexstreamline** [comment]
в поле номер повторения можем через слеш писать текущее с общим, типа 4/10

**Comment by Markeli** [comment]
О завершении сеанса судим по истечению времени (RemainingTime). Есть сомнения на счет привязки еще к номеру шагу и итерации, т.к. не понятно поведение в случае вызова реверса.
