### ISSUE TITLE
Повторы перезамер, обработка ошибок

### ISSUE THREAD

**Issue by Markeli** [alexstreamline/CardioMonitor#43]
- [x] В случае, если замерить давление (осуществить накачку) не удалось, ПО пробует повторить попытку еще 2 раза, после чего сообщает об ошибке, сеанс при этом не запускается. Это касается первого измерения. Что делать в остальных? Прерывать сеанс или сохранять значения как неизмеренные?
- [x] Можно различать ошибки, которые возникают в ходе работы с оборудованием. Предлагаю 3 типа ошибок - `ошибка подключения` (неверно заданы параметры), `разрыв соединения` (мы уже подключались к оборудования, но потеряли соединение, например, вырвали кабель) и `ошибка обработки` (ошибка парсинга, неверный пакет и т.д.). В случае возникновения ошибки `разрыв соединения` предлагаю уведомлять об этом пользователя и пытаться переподключиться. Если в этот момент необходимо измерить данные, но подключения нет, для этого угла будет сохранено значение `не удалось измерить`.

**Comment by alexstreamline** [comment]
1. Если не смогли при старте - не запускаем кровать. В дальнейшем кровать все равно будет катать по своему алгоритмы, так что просто пытаемся измерять данные, не получается - ну значит не судьба, кровать то все равно катает. К слову при реверсе все повторения от следующего до последнего отменяются, то есть кровать докатывает только текущее.
2. По поводу ошибок - давай, если теряем соединение - пытаемся подключиться с какой то периодичностью. Надо подумать, как вообще будем информировать об ошибках, можно какие то всплывающие окна, главное чтобы не так, как у нас было в той версии, когда надо обязательно нажать ОК. Мб еще какое то звуковое информирование в определенных случаях.
