### ISSUE TITLE
Действия с кроватью (при управлении с ПК и пульта)

### ISSUE THREAD

**Issue by alexstreamline** [alexstreamline/CardioMonitor#62]
Сейчас при нажатии на кнопки (старт/пауза, реверс, экстренная) просто отправляется команда на кровать и сразу после этого выполняется логика (лочатся кнопки, останавливается синхронайзер и т.д.). По идее, это не совсем корректно, ибо команда может не сработать на устройстве (или не дойти) по тем или иным причинам  и лучше выполнять логику по подтверждению от кровати (после отправки команды проверять статус и по нему понимать, все ли в норме). Кроме того, нужна реакция на изменения значения статуса кровати (то есть на нажатие кнопки на самом устройстве)

**Comment by alexstreamline** [comment]
UPD: При действиях с ПК нужно только отправлять команду на кровать, вся логика уходит в обработчик, который реагирует по изменению статуса на кровати

**Comment by alexstreamline** [comment]
upd2: соответственно менять UI элементы.

**Comment by Markeli** [comment]
Вернул логику к первоначальному варианту. Потому что в контроллере возникает путаница, и даже при нажатии, например, на кнопку реверса в приложении возникает сообщение о том, что оно вызвано с оборудования. Переписал отправку команд. Мы отправили команду, получили следующий ответ - считаем, что запрос выполнился. 
Исправлено в v0.2.
