### ISSUE TITLE
Последнее измерение при нескольких повторениях

### ISSUE THREAD

**Issue by alexstreamline** [alexstreamline/CardioMonitor#86]
Возникла такая ситуация: при завершении первого повторения повисло ожидание данных последнего измерения, при этом начался следующий цикл, ожидание в итоге так и не снялось в течение всего повторения.

**Comment by Markeli** [comment]
@alexstreamline, это дефект, который был у нас вечером. Я вроде поправил, но лучше перепроверить, что идет не так. Перевожу на тебя.

**Comment by Markeli** [comment]
@alexstreamline, у меня все ок. Если у тебя в течение дня не воспроизведется, предлагаю закрыть дефект.

**Comment by alexstreamline** [comment]
Не воспроизводилось.
