### ISSUE TITLE
Повторное измерение при достижении нуля

### ISSUE THREAD

**Issue by alexstreamline** [alexstreamline/CardioMonitor#87]
31,5 градус, 1 повторение. При финише накачка сработала 2 раза: при первом достижении нуля и в конце, после этого выскочили какие то левые цифры (19 00 – прошедшее время, 00- 34 – оставшееся, при том что сеанс завершился) После того как пришли данные по измерению давления – данные обновились на корректные.

**Comment by Markeli** [comment]
Значит, так говорит `BedController`. Проблема там. Данные собираются:
1. при старте вручную
2. при достижении контрольной точки
3. при завершении цикла (всегда выполняется ручной сбор)

1 и 3 обязательные и не зависят от контрольных точек. Надо проверить, что в определении контрольной точки нет ошибки. @alexstreamline, это тебе)

**Comment by Markeli** [comment]
@alexstreamline, я понял, почему вызывается дважды: первый раз потому, что в CheckPointChecker'е была указана эта итерация, а второй - потому что завершалось повторение, и мы принудительно собирали данные. Нужно убрать из чекеров повторения для последней итерации (для угла 0), и все будет ок.
