### ISSUE TITLE
Проблема миграции существующей БД

### ISSUE THREAD

**Issue by Markeli** [alexstreamline/CardioMonitor#91]
Баг с обновлялкой БД. Если база уже существует – ругается и обновить не предлагает (Статус БД – неизвестно, «Убедитесь что введенные параметры корректны, а у пользователя есть права на создание базы»). Смена имени бд на любую другую дает доступ к созданию нормальной базы.

**Comment by Markeli** [comment]
База должна не просто существовать, а быть созданной с 0 после введения механизма миграций, и в базе должна быть таблица `MigrationHistory`. Механизм миграции не работает с базой, которая у нас использовалась ранее (до июня). @alexstreamline, на какой базе было такое поведение?

**Comment by alexstreamline** [comment]
@Markeli  скорее всего она была старой, потому что проблема всплыла после обновления на ноуте, на котором стояла какая то старая версия

**Comment by Markeli** [comment]
Закрываю тогда дефект. Все равно они базу будут создавать с 0. Главное, чтобы этот сюрприз никого сильно не расстроил.
