### ISSUE TITLE
После создание БД невозможно выполнять операции с базой

### ISSUE THREAD

**Issue by Markeli** [alexstreamline/CardioMonitor#92]
После успешного создания БД сразу создать пользователя не получается – выход из приложения приводит к сбросу настроек подключения. Лечится только записью нужных параметров в app.config.

**Comment by Markeli** [comment]
Выход из приложения действительно будет выполнять сброс настроек, т.к. при запуске через IDE каждый раз копируется конфигурационный файл.

**Comment by Markeli** [comment]
С этим дефектом есть гемор. Сложно обновить подключение в runtime. @alexstreamline, давай будем выводить сообщение о необходимости перезапуска приложения?

**Comment by alexstreamline** [comment]
@Markeli  не вопрос, как удобнее

**Comment by Markeli** [comment]
@alexstreamline, будут выводить диалоговое окно с требованием перезапустить приложение для вступления изменений в силу.

**Comment by Markeli** [comment]
Проверять в v0.6 или более новой версии.
