### ISSUE TITLE
Блокировка кнопок реверса, паузы и продолжение при измерении по завершению цикла

### ISSUE THREAD

**Issue by alexstreamline** [alexstreamline/CardioMonitor#99]
Добавить события начала финального измерения в цикле и завершения измерения. Во viewModel блокировать на кнопки на время этого измерения.

**Comment by alexstreamline** [comment]
Либо добавить индикатор загрузки.

**Comment by Markeli** [comment]
Проверять в версии v0.6 или более новой версии
